name: flutter_qdmetro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.9+1001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^3.0.10
  ## 由于高德地图amap_flutter_location1.0.0的限制，所使用的最高版本为6.2.1
  geolocator: ^6.2.1
  package_info: ^0.4.0
  date_format: ^2.0.2
  # flutter_map: ^0.12.0
  # logging: ^0.11.4
  # latlong: ^0.6.1
  # stream_transform: ^1.2.0
  # build_resolvers: ^2.0.0
  rflutter_alert: ^2.0.2
  permission_handler: ^5.0.1
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.2
  cached_network_image: ^2.5.1
  #高德未适配flutter 2.x
  amap_flutter_location: ^1.0.0
  amap_flutter_map: ^1.0.0


  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # 由于高德地图依赖 stream_transform 1.2.0 不能将build_runner升至12
  build_runner: ^1.11.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # tabBar
    - images/tab_home.png
    - images/tab_home_selected.png
    - images/tab_mine.png
    - images/tab_mine_selected.png
    - images/tab_station.png
    - images/tab_station_selected.png

    # 主页
    - images/main_tab_scan.png
    - images/main_tab_scan_normal.png
    # 主页附近站点
    - images/metro_time_icon.png
    - images/main_station_arrow_up.png
    - images/metro_select_segment_background.png
    # 主页底部do u know
    - images/main_bottom_left_top_bg.png
    - images/main_bottom_right_bottom_bg.png
    - images/main_bottom_title_bg.png

    #地图
    - images/map_index_footer_transfer.png
    - images/map_index_footer_container_background.png

    #个人中心
    - images/uc_arrow_right.png
    - images/uc_header_background.png
    - images/uc_header_item_container_background.png
    - images/uc_icon_wallet.png
    - images/uc_icon_discount.png
    - images/uc_icon_integral.png
    - images/uc_authenticated.png #实名认证
    ## 个人中心的固定icon
    - images/uc_icon_zhifu.png
    - images/uc_icon_jilu.png
    - images/uc_icon_fapiao.png
    - images/uc_icon_message.png
    - images/uc_icon_kefu.png
    - images/uc_icon_shoucang.png
    - images/uc_icon_share.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
